import type { AxiosRequestConfig } from 'axios';
import { createRezoInstance, type RezoInstance, type AdapterFunction } from '../src/core/rezo';
import type { RezoResponse, RezoStreamResponse } from '../src/types/response';
import node from '../src/platform/node';
import bun from '../src/platform/bun';
import deno from '../src/platform/deno';
import browser from '../src/platform/browser';
import worker from '../src/platform/worker';
import reactNative from '../src/platform/react-native';
import httpEntry from '../src/adapters/entries/http';
import http2Entry from '../src/adapters/entries/http2';
import fetchEntry from '../src/adapters/entries/fetch';
import curlEntry from '../src/adapters/entries/curl';
import xhrEntry from '../src/adapters/entries/xhr';
import nativeEntry from '../src/adapters/entries/react-native';
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
type Assert<T extends true> = T;
declare const rezo: RezoInstance<{ id: number }>;
declare const adapter: AdapterFunction;
declare const init: RequestInit;
declare const axios: AxiosRequestConfig;
const url = 'https://example.invalid';
const request = new Request(url);
void rezo(url, init);
void rezo(request, init);
void rezo({ url, method: 'POST', body: new Uint8Array([1]) });
void rezo.request(url, init);
void rezo.request(request, init);
void rezo.request(axios);
void rezo.request(url, axios);
void rezo.request('child', { prefixUrl: url, searchParams: new URLSearchParams('x=1&x=2') });
const text = rezo(url, { responseType: 'text' });
const buffer = rezo.request(url, { responseType: 'arrayBuffer' });
const stream = rezo(request, { responseType: 'stream' });
const native = rezo({ url });
const custom = rezo.request<{ custom: true }>(url, { responseType: 'json' });
declare const mode: 'text' | 'arrayBuffer';
const union = rezo(url, { responseType: mode });
const created = rezo.create<{ created: true }>().request(url);
const factory = createRezoInstance<{ factory: true }>(adapter)(url);
declare const optionalMode: { responseType?: 'text' | 'stream' };
const optional = rezo(url, optionalMode);
const explicitStream = rezo<{ ignored: true }>(url, { responseType: 'stream' });
const explicitBuffer = rezo.request<{ ignored: true }>(url, { responseType: 'arrayBuffer' });
const explicitText = rezo<{ ignored: true }>(url, { responseType: 'text' });
const explicitDefault = rezo<{ custom: true }>(url);
const explicitOptional = rezo<{ custom: true }>(url, optionalMode);
type Text = Assert<Equal<Awaited<typeof text>, RezoResponse<string>>>;
type Buffer = Assert<Equal<Awaited<typeof buffer>, RezoResponse<ArrayBuffer>>>;
type Stream = Assert<Equal<Awaited<typeof stream>, RezoStreamResponse>>;
type Native = Assert<Equal<Awaited<typeof native>, RezoResponse<{ id: number }>>>;
type Custom = Assert<Equal<Awaited<typeof custom>, RezoResponse<{ custom: true }>>>;
type Union = Assert<Equal<Awaited<typeof union>, RezoResponse<string> | RezoResponse<ArrayBuffer>>>;
type Created = Assert<Equal<Awaited<typeof created>, RezoResponse<{ created: true }>>>;
type Factory = Assert<Equal<Awaited<typeof factory>, RezoResponse<{ factory: true }>>>;
type Optional = Assert<Equal<Awaited<typeof optional>, RezoResponse<string> | RezoStreamResponse | RezoResponse<{ id: number }>>>;
type ExplicitStream = Assert<Equal<Awaited<typeof explicitStream>, RezoStreamResponse>>;
type ExplicitBuffer = Assert<Equal<Awaited<typeof explicitBuffer>, RezoResponse<ArrayBuffer>>>;
type ExplicitText = Assert<Equal<Awaited<typeof explicitText>, RezoResponse<string>>>;
type ExplicitDefault = Assert<Equal<Awaited<typeof explicitDefault>, RezoResponse<{ custom: true }>>>;
type ExplicitOptionalIncludesStream = Assert<Equal<Extract<Awaited<typeof explicitOptional>, RezoStreamResponse>, RezoStreamResponse>>;

for (const entry of [node, bun, deno, browser, worker, reactNative, httpEntry, http2Entry, fetchEntry, curlEntry, xhrEntry, nativeEntry]) {
  void entry(request, init);
  void entry.request(url, axios);
  void entry.request({ url, searchParams: { zero: 0 }, data: new Uint8Array([1]) });
  const entryStream = entry(request, { responseType: 'stream' });
  const entryText = entry.create<{ custom: true }>().request(url, { responseType: 'text' });
  type EntryStream = Assert<Equal<Awaited<typeof entryStream>, RezoStreamResponse>>;
  type EntryText = Assert<Equal<Awaited<typeof entryText>, RezoResponse<string>>>;
}
// @ts-expect-error unknown mode stays invalid
void rezo(url, { responseType: 'invalid-mode' });
// @ts-expect-error shared native spelling remains case-sensitive
void rezo.request(url, { responseType: 'TEXT' });
